name: Build Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - apps/backend/**
      - apps/frontend/**
      - infra/docker/**
      - requirements.txt
      - package-lock.json
      - package.json
  workflow_dispatch:

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            dockerfile: infra/docker/backend.Dockerfile
            tag: backend
          - name: frontend
            dockerfile: infra/docker/frontend.Dockerfile
            tag: frontend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Log in to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ghcr.io/zephyrzenn/flashainews-${{ matrix.tag }}:ci
            ${{ secrets.ACR_REGISTRY }}/${{ secrets.ACR_NAMESPACE }}/flashainews-${{ matrix.tag }}:ci
