name: Deploy via Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: SSH & Deploy with Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT || '22' }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            # 切到项目目录
            cd ~/FlashAiNews

            echo "Pull latest Git code..."
            git pull origin main

            echo "Rebuild and restart via Docker Compose..."

            docker-compose up -d --build

            echo "Services restarted at $(date)"
